[Metadata]
Name=macOS Light
Version=1
Author=lonr <https://lonr.eu.org>
Description=macOS-like color scheme for Fcitx5 Rime (light)
ScaleWithDPI=True

[InputPanel]
NormalColor=#494949
HighlightColor=#ffffff
HighlightBackgroundColor=#005AD8
EnableBlur=True
FullWidthHighlight=True
PageButtonAlignment=Bottom

[InputPanel/Background]
Image=panel.svg
Color=#ffffff
BorderColor=#ffffff
BorderWidth=0

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Image=highlight.svg
Color=#ffffff
BorderColor=#ffffff00
BorderWidth=0

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=4
Bottom=4

[InputPanel/ContentMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/TextMargin]
Left=15
Right=15
Top=8
Bottom=8

[InputPanel/ShadowMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu]
NormalColor=#494949
HighlightColor=#ffffff
HighlightCandidateColor=#494949
Spacing=0

[Menu/Background]
Color=#f1f2f2
BorderColor=#c0c0c0
BorderWidth=0

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#005AD8

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#c0c0c0

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
